### ISSUE TITLE
Non upstream hangups

### ISSUE THREAD

**Issue by diggit** [ZeWaren/jabber-hangouts-transport#6]
Is it necessary to have separate version of hangups library? Isn't current upstream version ok?

**Comment by ZeWaren** [comment]
That's because I did a couple _improvements_ in the library.
I planned to push them upstream, but I didn't get any time to do it.
Right now the transport is still in some kind of _alpha_ state, but in the future I completely agree that we should not embed our own version of the library.

**Comment by rozzin** [comment]
> That's because I did a couple improvements in the library.
> I planned to push them upstream, but I didn't get any time to do it.
> Right now the transport is still in some kind of alpha state, but in the future I completely agree that we should not embed our own version of the library.

Reverse-engineering projects don't necessarily ever get out of alpha state--a hostile back end randomly changing things without concern for compliance with any public spec is enough to make it so :(

See issue #14, for example.

It'd probably be easier for us to work through that issue (and others like it) if our "hangups" tree was a submodule, because then we'd be able to try merging the upstream changes into it. Though probably it'd make sense to have that submodule reference _your own fork_ of the hangups repo (so that you can continue to fold in improvements as necessary without having to wait for upstream).
